# Generated by Django 2.1.5 on 2019-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheet_pdf',
            field=models.FileField(default='default.jpg', upload_to='sheet_music'),
        ),
    ]
