# Generated by Django 2.1.5 on 2019-01-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_sheet_sheet_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='author',
            new_name='composer',
        ),
        migrations.RenameField(
            model_name='sheet',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='sheet',
            name='initial_key',
            field=models.CharField(default='c', max_length=16),
            preserve_default=False,
        ),
    ]
