# Generated by Django 2.1.5 on 2019-01-07 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheet', '0003_auto_20190107_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sheet',
            name='composer',
            field=models.TextField(),
        ),
    ]
